# Generated by Django 4.2 on 2023-04-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("city_guide", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="city_guide.question",
            ),
        ),
    ]
