# Generated by Django 4.2 on 2023-04-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city_guide", "0002_comment_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="media_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
